### ISSUE TITLE
docs/editor: add editor setup guide

### ISSUE THREAD

**Issue by domenkozar** [nix-community/nixd#100]
Most users would like to know just one thing: how to setup their editor to use nixd.

It would be good to document that in the README.md, in my case VSCode.

**Comment by inclyc** [comment]
Thanks, use the plugin Nix IDE and set the server path to `nixd` shall work out of box.

> It would be good to document that in the README.md, in my case VSCode.

I would like to do that today.

**Comment by inclyc** [comment]
https://discourse.nixos.org/t/nixd-nix-language-server/28910/4?u=inclyc
