### ISSUE TITLE
vendor: the program SIGSEGV on darwin

### ISSUE THREAD

**Issue by inclyc** [nix-community/nixd#107]
Link: #36

**Comment by inclyc** [comment]
Opened aarch64-darwin & x86_64-darwin machines locally, looks like it's different ABI or something incompatible. On aarch64-darwin it SEGSEGV immediately on loading, and on x86_64 it fails while calling some nix libraries (and SIGSEGV inside)

**Comment by inclyc** [comment]
https://github.com/nix-community/nixd/issues/133#issuecomment-1592595147

**Comment by inclyc** [comment]
@srid @arianvp, I'm currently using a Macbook Air M1 (running asahi & macOS) as well as an Intel Macbook Pro, and I am pleased to have resolved this issue. However, as mentioned earlier, there are still many missing features and enhancements that need to be addressed, and unfortunately, I do not have the bandwidth to work on this one at the moment.

I would like to note that there are no Linux-specific APIs used in nixd. If this issue is fixed on your machine, I would greatly appreciate it and would gladly accept pull requests.

**Comment by srid** [comment]
Cheers @inclyc. C++ hates me, and I'm also occupied otherwise. But I'd be happy to test any patches or PRs on my aarch64-darwin machine.
