### ISSUE TITLE
vendor: do not suggest using overlay to avoid incompatible nixpkgs revision 

### ISSUE THREAD

**Issue by gaelreyrol** [nix-community/nixd#109]
Hi,

I am using the 1.0.0 revision: e2ba0c402a1a73253f6ffaca9cb5ce4b9321e313 and followed the usage section.

When building the I get multiple compilation errors, here is the log output:
https://gist.github.com/gaelreyrol/6ff901f8f171abacff8d2d06ebedab6d

Am I missing something?

**Comment by inclyc** [comment]
Are you overriding nixpkgs revision? Something like https://github.com/nix-community/nixd/issues/53#issuecomment-1574936342

**Comment by gaelreyrol** [comment]
I did but I removed the override when I've seen those failures and it does not change anything.

**Comment by inclyc** [comment]
> I did but I removed the override when I've seen those failures and it does not change anything. Here is my actual flake.lock: https://gist.github.com/gaelreyrol/6ff901f8f171abacff8d2d06ebedab6d#file-flake-lock

Looks like you did not update the lock after removing such overriding? The locked ref in this lock of nixpkgs for nixd is still indirectly reference to "nixpkgs".

**Comment by inclyc** [comment]
> Are you overriding nixpkgs revision? Something like [#53 (comment)](https://github.com/nix-community/nixd/issues/53#issuecomment-1574936342)

Actually there is a PR https://github.com/nix-community/nixd/pull/98 to fix nix revision on 2.16.x, might be useful to address this issue.

**Comment by gaelreyrol** [comment]
> > I did but I removed the override when I've seen those failures and it does not change anything. Here is my actual flake.lock: https://gist.github.com/gaelreyrol/6ff901f8f171abacff8d2d06ebedab6d#file-flake-lock
> 
> Looks like you did not update the lock after removing such overriding? The locked ref in this lock of nixpkgs for nixd is still indirectly reference to "nixpkgs".

Mmh it is referencing this node which refers to the unstable branch:
```
{
    "nixpkgs": {
      "locked": {
        "lastModified": 1686398752,
        "narHash": "sha256-nGWNQVhSw4VSL+S0D0cbrNR9vs9Bq7rlYR+1K5f5j6w=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "a30520bf8eabf8a5c37889d661e67a2dbcaa59e6",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixpkgs-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    }
}
```

**Comment by inclyc** [comment]
> > > I did but I removed the override when I've seen those failures and it does not change anything. Here is my actual flake.lock: https://gist.github.com/gaelreyrol/6ff901f8f171abacff8d2d06ebedab6d#file-flake-lock
> > 
> > 
> > Looks like you did not update the lock after removing such overriding? The locked ref in this lock of nixpkgs for nixd is still indirectly reference to "nixpkgs".
> 
> Mmh it is referencing this node which refers to the unstable branch:
> 
> ```
> {
>     "nixpkgs": {
>       "locked": {
>         "lastModified": 1686398752,
>         "narHash": "sha256-nGWNQVhSw4VSL+S0D0cbrNR9vs9Bq7rlYR+1K5f5j6w=",
>         "owner": "NixOS",
>         "repo": "nixpkgs",
>         "rev": "a30520bf8eabf8a5c37889d661e67a2dbcaa59e6",
>         "type": "github"
>       },
>       "original": {
>         "owner": "NixOS",
>         "ref": "nixpkgs-unstable",
>         "repo": "nixpkgs",
>         "type": "github"
>       }
>     }
> }
> ```

AFAIK, unstable branch changed nix version from 2.15 -> 2.16 weeks ago, maybe your branch still points to 2.15 though. Maybe the best solution here is to run:

```
nix flake update
```

to update the lock. 

Nixpkgs packaging & #98 generally fix this issue, nixd is a project written a month ago, thanks for giving it a try :).

**Comment by inclyc** [comment]
Our codebase bumped nix version to 2.16 in #86. You can see several APIs changed in that PR.

**Comment by ncfavier** [comment]
I'm also hitting compilation failures by using the overlay. If only a particular version of nixpkgs is supported, then the documentation should not recommend using the overlay.

**Comment by inclyc** [comment]
> I'm also hitting compilation failures by using the overlay. If only a particular version of nixpkgs is supported, then the documentation should not recommend using the overlay.

Thanks for suggesstion :)

I would like to maintain packaging in nixpkgs then.

**Comment by gaelreyrol** [comment]
I modified a little bit the derivation so It can be customized and updated "automatically".

```nix
{ stdenv
, lib
, fetchFromGitHub
, meson
, ninja
, cmake
, pkg-config
, lit
, nixUnstable
, boost182
, gtest
, llvmPackages_16
, libbacktrace
, nix-update-script

  # The default Nix package to use as build dependency
, nixPackage ? nixUnstable
}:

let
  filterMesonBuild = builtins.filterSource
    (path: type: type != "directory" || baseNameOf path != "build");
in
stdenv.mkDerivation rec {
  pname = "nixd";
  version = "1.0.0";

  src = filterMesonBuild (fetchFromGitHub {
    owner = "nix-community";
    repo = "nixd";
    rev = version;
    hash = "sha256-kTDPbsQi9gzFAFkiAPF+V3yI1WBmILEnnsqdgHMqXJA=";
  });

  nativeBuildInputs = [
    meson
    ninja
    cmake
    pkg-config

    # Testing only
    lit

    (lib.getDev nixPackage)
    (lib.getDev boost182)
    (lib.getDev gtest)
    (lib.getDev llvmPackages_16.llvm)
    llvmPackages_16.clang
  ];

  buildInputs = [
    libbacktrace
    nixPackage
    gtest
    (lib.getDev boost182)
    (lib.getLib llvmPackages_16.llvm)
  ];

  CXXFLAGS = "-include ${lib.getDev nixPackage}/include/nix/config.h";

  passthru.updateScript = nix-update-script { };

  meta = {
    description = "Nix language server";
    homepage = "https://github.com/nix-community/nixd";
    changelog = "https://github.com/nix-community/nixd/releases/tag/${version}";
    license = lib.licenses.lgpl3Plus;
    maintainers = [ ];
    platforms = lib.platforms.unix;
  };
}
```

That way for example it can be overwritten with:
```
(final: prev: {
  nixd = prev.nixd.override {
    nixPackage = prev.nixVersions.nix_2_16;
  }
})
```
