### ISSUE TITLE
segfaults on aarch64-darwin

### ISSUE THREAD

**Issue by arianvp** [nix-community/nixd#133]
I actually don't know how to find coredumps on MacOS but every command segfaults immediately:

```
arian@Arians-MacBook-Pro nixos-stuff % nixd
zsh: segmentation fault  nixd
arian@Arians-MacBook-Pro nixos-stuff % nixd --help
zsh: segmentation fault  nixd --help
```

**Comment by inclyc** [comment]
Duplicate to https://github.com/nix-community/nixd/issues/107

**Comment by inclyc** [comment]
I guess it may just a packaging issue, because actually there is no linux-specific APIs used.

**Comment by inclyc** [comment]
> I actually don't know how to find coredumps on MacOS but every command segfaults immediately:

I have seen these dumps, in #107 , but currently have no bandwidth to resolve this issue. (Working static analysis such as rename).
