### ISSUE TITLE
Feature request: serve the Debug Adapter Protocol (DAP)

### ISSUE THREAD

**Issue by hab25** [nix-community/nixd#208]
Debuggers are very helpful for development; nix has debugging capabilities: https://nixos.org/manual/nix/stable/release-notes/rl-2.9.html#:~:text=Running%20Nix%20with-,the%20new%20%2D%2Ddebugger,-flag%20will%20cause

About DAP: https://microsoft.github.io/debug-adapter-protocol/

Note: I don't know how feasible this currently is for `nixd`, nor if it would be better to have it as a separate project instead.

**Comment by inclyc** [comment]
> Note: I don't know how feasible this currently is for nixd, nor if it would be better to have it as a separate project instead.

Nice idea, however the code base for nixd might be unsuitable for providing a DAP, maybe better for a separate project.

**Comment by hab25** [comment]
> maybe better for a separate project.

I would expect the implementations of both protocols to use a lot of the same in-memory data; I would expect having a single process for both to bring noticeable performance benefits. WDYT @inclyc ?

**Comment by inclyc** [comment]
> I would expect the implementations of both protocols to use a lot of the same in-memory data 

Hmm, for example?

After a quick reading the specification, the DAP adapter is something like a bridge between nix debugger and the DAP client, then what kinds of data structures are expected to be shared with the LSP (not sure, just ask)?

The nixd library provides some useful components (e.g. libnixdExpr, libnixdAST) for static analysis, might be useful for DAP, maybe just linking with these libraries is sufficient for DAPs.

**Comment by inclyc** [comment]
Closing this as "not planned" as it is not planned to be implemented in this project. However, I think it is worth a try in a separated project (when I have enough bandwidth to exploring DAPs).

**Comment by lf-** [comment]
Actually, @DieracDelta is working on something like this under the name nix-dap. I am unsure as to its progress, but I believe it is NLNet funded.
