### ISSUE TITLE
[feature] provide a json schema for .nixd.json

### ISSUE THREAD

**Issue by Freed-Wu** [nix-community/nixd#222]
Why not provide a json schema to <https://www.schemastore.org/json/> to provide language server support for `.nixd.json`? It can make users to edit `.nixd.json` easier. TIA!

**Comment by inclyc** [comment]
Would you like to do this? I'm not very familiar with this field.

**Comment by Freed-Wu** [comment]
Is there any standard document to describe the structure of `.nixd.json`? And is it enough stable (that is it will not change more frequently)?

**Comment by Freed-Wu** [comment]
PS: The full information about json schema can be found in <https://json-schema.org>.

**Comment by inclyc** [comment]
> Is there any standard document to describe the structure of

It should has the same fields as https://github.com/nix-community/nixd/blob/0d57fd2cded203d6e480e77644ee2faac75a0e80/nixd/include/nixd/Support/JSONSerialization.h#L58

And all fields are optional.

> And is it enough stable (that is it will not change more frequently)?

Nixd itself is written a month ago, the configuration may might not be stable then.

**Comment by Freed-Wu** [comment]
> Nixd itself is written a month ago, the configuration may might not be stable then.

OK, maybe we can wait that it will be enough stable and more accurate document will be determined :+1:

**Comment by Freed-Wu** [comment]
A PR is provide by <https://github.com/SchemaStore/schemastore/pull/3059>.
