### ISSUE TITLE
Consider putting `nix develop github:nix-community/nixd#vscodium` at top of readme

### ISSUE THREAD

**Issue by ParetoOptimalDev** [nix-community/nixd#223]
I was unable to get this working with vscode and forgot about it a few weeks. Upon coming back I realized I'd missed the piece about using the demo of `nix develop github:nix-community/nixd#vscodium`.

I bet a lot more users will get hooked so to speak if you encourage trying it out with this expression first.

**Comment by inclyc** [comment]
CC @Ruixi-rebirth
