### ISSUE TITLE
Support external modules Home Manager

### ISSUE THREAD

**Issue by dvetutnev** [nix-community/nixd#251]
nixd can be inspect options from external HM modules? Such as [nixvim](https://github.com/nix-community/nixvim)?

**Comment by inclyc** [comment]
> @dvetutnev :
> nixd can be inspect options from external HM modules?

Yes. We do generally support all nixpkgs module systems. If you import nixvim as your HM module, it is expected to see options from it.

But "submodules" (`foo.<name>.bar`) which needs special handling) are currently not supported, see: #106

**Comment by dvetutnev** [comment]
Because it's different?
```nix
nix-repl> homeConfigurations."dvetutnev@vulpecula".options.programs.nixvim
{ __toString = «lambda @ /nix/store/1rp9mgpy83k4w11gi58hqfcqhk3nnahp-source/lib/modules.nix:807:22»; _type = "option"; declarations = [ ... ]; default = { ... }; definitions = [ ... ]; definitionsWithLocations = [ ... ]; files = [ ... ]; highestPrio = 100; isDefined = true; loc = [ ... ]; options = [ ... ]; type = { ... }; value = { ... }; }

nix-repl> homeConfigurations."dvetutnev@vulpecula".options.programs.git   
{ aliases = { ... }; attributes = { ... }; delta = { ... }; diff-so-fancy = { ... }; difftastic = { ... }; enable = { ... }; extraConfig = { ... }; hooks = { ... }; ignores = { ... }; includes = { ... }; iniContent = { ... }; lfs = { ... }; package = { ... }; signing = { ... }; userEmail = { ... }; userName = { ... }; }
```

**Comment by inclyc** [comment]
Yes, it is actually a submodule: https://github.com/nix-community/nixvim/blob/b8c3385599e90f1252eb3318dd00dd763dcc56f6/wrappers/hm.nix#L19

**Comment by inclyc** [comment]
Can I close this as duplicated to #106 ?

**Comment by dvetutnev** [comment]
Already.

**Comment by inclyc** [comment]
Duplicate to #106
