### ISSUE TITLE
Helix editor config example

### ISSUE THREAD

**Issue by GlennWSo** [nix-community/nixd#258]
I don't understand how to configure helix to use this lsp

**Comment by inclyc** [comment]
> I don't understand how to configure helix to use this lsp

Sorry I do not use this editor and cannot give you any editor-specific advice. The language server itself should be editor-agnostic I suppose

**Comment by KiaraGrouwstra** [comment]
it seems one can use:

```nix
  programs.helix = {
    enable = true;
    languages = {
      language-server = {
        nixd.command = "${pkgs.nixd}/bin/nixd";
      };
      language = [
        {
          name = "nix";
          language-servers = ["nixd"];
        }
      ];
    };
  };
```

what i'm still wondering about is how one is supposed to pass `nixd` its [configuration](https://github.com/nix-community/nixd/blob/main/nixd/docs/configuration.md) from a different editor.

**Comment by dj8yfo** [comment]
@inclyc  helix works with 2.x version of nixd; nixd is awesome
