### ISSUE TITLE
goto definition for nixos options

### ISSUE THREAD

**Issue by lf-** [nix-community/nixd#265]
Since my PR https://github.com/NixOS/nixpkgs/pull/249243 has been merged, we have non-garbage character level position information for about 90% of nixos options available under options.OPTION.declarationPositions, in the format of unsafeGetAttrPos.

This could, at least theoretically, form the basis of goto definition on nixos options. I expect this may have similar challenges to implement as https://github.com/nix-community/nixd/issues/174, namely, figuring out what the actual option name is, but once those are resolved, this should be very possible.

**Comment by inclyc** [comment]
This is already implemented in https://github.com/nix-community/nixd/pull/93 ?

**Comment by lf-** [comment]
Yes, you're right; I missed that one. I think you may be able to use the declarationPositions attribute for a more direct way of getting to the attribute location which would be more reliable in certain cases (but falls over in different cases).

**Comment by inclyc** [comment]
This feature gets implemented in #433. 

@lf-
