### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Freed-Wu** [nix-community/nixd#275]
I try to package it to ArchLinux: <https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nixd>
However meet some build error. I am not familar with meson :cry:
Is it because Archlinux's nixd doesn't have some unstable API this project used? TIA!

[build log](https://pastebin.pl/view/10710d36)

**Comment by inclyc** [comment]
> /usr/include/nix/globals.hh:215:11: error: could not convert ‘{((nix::Settings*)this), &lt;expression error&gt;, "system", "\012          The system type of the current Nix installation.\0 

I think the error is caused by using incorrect version of nix.

> Is it because Archlinux's nixd doesn't have some unstable API this project used

No, we use some unstable APIs from C++ nix, and use a different version probably leads to compilation issues (like this).
