### ISSUE TITLE
Can't get flake options working in coc-nvim

### ISSUE THREAD

**Issue by matt1432** [nix-community/nixd#290]
I've been trying to get options suggestions to work but they're not coming up. The errors/diagnostics do show up and the formatting command is recognized.

My flake is located at /home/matt/.nix with these in my inputs:

```nix
...
    flake-compat = {
      type = "github";
      owner = "inclyc";
      repo = "flake-compat";

      flake = false;
    };

    nixd = {
      type = "github";
      owner = "nix-community";
      repo = "nixd";
    };
...
```

Using the overlay:

```nix
{nixd, ...}: {
  nixpkgs.overlays = [
    nixd.overlays.default
  ];
}
```

With these settings in the home-manager module (I only put the ones concerning nixd):
```nix
{...}: let
  user = "matt";
  hostName = "wim";
in {
  home = {
    file = {
      ".nix/.nixd.json".text = builtins.toJSON {
        eval = {
          target = {
            args = ["-f" "default.nix"];
            installable = "nixosConfigurations.${hostName}.config.system.build.toplevel";
          };
          workers = 1;
        };
        formatting.command = "alejandra";
        options = {
          enable = true;
          target = {
            args = [];
            installable = ".#nixosConfigurations.${hostName}.options";
          };
        };
      };

      ".nix/default.nix".text =
        /*
        nix
        */
        ''
          (import
            (
              let lock = builtins.fromJSON (builtins.readFile /home/${user}/.nix/flake.lock); in
              fetchTarball {
                url = "https://github.com/edolstra/flake-compat/archive/''${lock.nodes.flake-compat.locked.rev}.tar.gz";
                sha256 = lock.nodes.flake-compat.locked.narHash;
              }
            )
            { src = /home/${user}/.nix; }
          ).defaultNix
        '';
    };
  };

  programs = {
    neovim = {
      ...
      extraPackages = with pkgs; [nixd];

      coc = optionalAttrs neovimIde {
        enable = true;
        settings = {
          colors.enable = true;
          coc.preferences.formatOnType = true;
          diagnostic.checkCurrentLine = true;
          inlayHint.enable = false;

          languageserver = {
            # Nix
            nix = {
              command = "nixd";
              args = ["-log=debug"];
              filetypes = ["nix"];
              rootPatterns = [".nixd.json"];
            };
          };
        };
      };
    };
  };
}
```

**Comment by inclyc** [comment]
> Using the overlay:

Have you tried this package in nixpkgs?

**Comment by matt1432** [comment]
It does the same thing unfortunately

**Comment by inclyc** [comment]
How about examples here? https://github.com/nix-community/nixd/blob/main/nixd/docs/examples/options/nixos/module.nix

**Comment by inclyc** [comment]
You may `cd` to that directory before launching the editor, since we rely on relative paths.

**Comment by matt1432** [comment]
That example does work for me. So the issue is with the flake setup.

**Comment by matt1432** [comment]
Here's my whole config if you'd like to take a look:
https://git.nelim.org/matt1432/nixos-configs/src/branch/nixd

**Comment by inclyc** [comment]
Our option completion module shall works fine for flakes (out of box) and does not need flake-compat.

What's the nix repl say about 

nixosConfigurations.wim.options?


> nixosConfigurations.wim.config.system.build.toplevel

Just an offtopic note, I think this path is too 'deep' and has high resource consumption for eval. Maybe

nixosConfigurations.wim.config

is sufficient. We have mechanism to do necessary eval on-demand.

**Comment by inclyc** [comment]
Also there is a planned migration to partially rewrite this project in Rust. I'd expect end-user experience would be improved a lot in that branch.
