### ISSUE TITLE
Support for multiple options

### ISSUE THREAD

**Issue by naythanN** [nix-community/nixd#311]
Greetings,

I wanted to ask if accepting multiple options is planned or is there a known workaround.

I use vscode, and from the docs as I understand you can not have completions for nixos options and home manager options at the same time. Maybe activating by directory or some other way.

If there isn't a workaround and it is planned, I am willing to try to help.

Nice project btw

Regards,

**Comment by inclyc** [comment]
Somehow duplicated to 

- #213 
- #272

> I wanted to ask if accepting multiple options is planned or is there a known workaround.

The only "workaround" is switching config file at runtime. Since `workspace/configuration` can be updated on-the-fly.

> If there isn't a workaround and it is planned, I am willing to try to help.

I think maybe a code action or some simple regex rules are acceptable, or just support pre-folder configuration or somehow.
