### ISSUE TITLE
Now sees attribute set arguments as regular attribute sets and throws ; expected warnings

### ISSUE THREAD

**Issue by BirdeeHub** [nix-community/nixd#325]
Now sees attribute set arguments as regular attribute sets and throws = and ; expected warnings
Something in the last couple days broke it. I really have no idea what but it looks like this

![Screenshot_2024-01-25_21-27-04](https://github.com/nix-community/nixd/assets/85372418/b5e951e3-2eb7-4c5e-88a0-c0a093fcc124)

Edit:

the last working commit Ive found so far is 5b338749ab1eb158ba17d56a249ec28c5fce40c6

The commit immediately after it, ccf98152596d7688946629ac152ae9a7a72b70b2 actually makes the lsp client crash completely

**Comment by inclyc** [comment]
> Now sees attribute set arguments as regular attribute sets and throws = and ; expected warnings Something in the last couple days broke it. I really have no idea what but it looks like this
> 
> ![Screenshot_2024-01-25_21-27-04](https://private-user-images.githubusercontent.com/85372418/299886603-b5e951e3-2eb7-4c5e-88a0-c0a093fcc124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDg2NDQsIm5iZiI6MTcwNjI0ODM0NCwicGF0aCI6Ii84NTM3MjQxOC8yOTk4ODY2MDMtYjVlOTUxZTMtMmViNy00YzVlLTg4YTAtYzBhMDkzZmNjMTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA1NTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTk5NmZmZTAyYTk3YTY4NjczNWQzYzMwYjgzY2IyNmU2MzVkZjBkYTg0MTA0ZWQ3N2EyNjJjNDNjY2NjN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h6nvuiUXzIPpLgbMQSwO-Z8ld4uAuKulO9Bfm_fCBq0)
> 
> Edit:
> 
> the last working commit Ive found so far is [5b33874](https://github.com/nix-community/nixd/commit/5b338749ab1eb158ba17d56a249ec28c5fce40c6)
> 
> The commit immediately after it, [ccf9815](https://github.com/nix-community/nixd/commit/ccf98152596d7688946629ac152ae9a7a72b70b2) actually makes the lsp client crash completely

Thanks for contribution!

Looks like you are on the unstable `nixd-next` branch, as noted in README.md[^readme], it is on an early stage and working in progress. Pictures shown here are actually lambdas, which may not yet implemented. See #283 for the progress.

[^readme]: [WIP note in README.md](https://github.com/nix-community/nixd/blob/3686d6c02b7d60962c882f4d16f0431cdc0def95/README.md?plain=1#L9)

**Comment by inclyc** [comment]
Are you using the overlay or something related to default branch in this repo? We have stable releases in `nixpkgs` (`pkgs.nixd`) perhaps you can use that package.

**Comment by inclyc** [comment]
I just set the default branch back to `main`, to avoid such issue...

**Comment by BirdeeHub** [comment]
Im using the overlay. I have it pinned now to the last working version in my nix config. Is the newest version not supported or something? If this branch is a work in progress still I will leave it pinned I suppose?

**Comment by BirdeeHub** [comment]
https://github.com/BirdeeHub/nixCats-nvim/tree/nixCats-5.0.0

Im using this, although it seems to happen with the nixos and home manager modules as well.

**Comment by inclyc** [comment]
> Im using the overlay. I have it pinned now to the last working version in my nix config. Is the newest version not supported or something? If this branch is a work in progress still I will leave it pinned I suppose?

Maybe just use the latest stable release. Normally main branch is always working and has no breaking changes, however `nixd-next` is a big refactor (nearly a complete rewrite with complete new parser, semantic analysis and architecture), and it has many commits ahead main branch.

**Comment by BirdeeHub** [comment]
hmmm okok. I was unaware. Well, FYI then, nixd next has broken attribute set arguments XD

**Comment by inclyc** [comment]
> Im using the overlay. I have it pinned now to the last working version in my nix config. Is the newest version not supported or something? If this branch is a work in progress still I will leave it pinned I suppose?

I would like suggest completely not using nixd flake overlay, if you are not developers. Just use nixpkgs version, that's also maintained by me.

**Comment by inclyc** [comment]
> hmmm okok. I was unaware. Well, FYI then, nixd next has broken attribute set arguments XD

That's not "broken", just completely NOT implemented yet. :(

**Comment by BirdeeHub** [comment]
> > Im using the overlay. I have it pinned now to the last working version in my nix config. Is the newest version not supported or something? If this branch is a work in progress still I will leave it pinned I suppose?
> 
> I would like suggest completely not using nixd flake overlay, if you are not developers. Just use nixpkgs version, that's also maintained by me.

Somehow, when I was first looking for nixd on nixpkgs I was unable to find it?! IDK how I found it just fine this time....

This is good news that I can remove that flake input from nixCats-nvim

**Comment by inclyc** [comment]
![image](https://github.com/nix-community/nixd/assets/36667224/d595f491-51f0-4b92-b089-bd4c3e061dba)

These features are not supported yet, and may working a few days later.

**Comment by BirdeeHub** [comment]
Do I close this issue then? leave it open? glad I found out I was using the wrong version I guess
