### ISSUE TITLE
feature request: way to get code for options

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nix-community/nixd#336]
hi there,

when trying to port one's setup for a given program to nix, a common task seems to be checking the [available options](https://search.nixos.org/options?query=programs.firefox), then putting those into nix code, configuring desired values.

it would be nice if nixd could help generate nix code based on the available default/example values (if not also option descriptions), e.g. given an option `programs.firefox.enable`:

```nix
# Whether to enable the Firefox web browser.
programs.firefox.enable = false;
# programs.firefox.enable = true;
```

... except ideally for an entire option group (e.g. `programs.firefox`) at a time, ideally recursively.

originally [posted at discourse](https://discourse.nixos.org/t/way-to-get-code-for-options/38954)

**Comment by inclyc** [comment]
This looks trivial to impl, perhaps you can see this feature in later a few releases.

**Comment by inclyc** [comment]
Maybe for lsp I would like add a new code action, or completion snippet.

**Comment by inclyc** [comment]
In #415 you will get code snippet filled with code example. Thus linking that PR.
