### ISSUE TITLE
misc: platform testing

### ISSUE THREAD

**Issue by inclyc** [nix-community/nixd#36]
Currently the binaries are only tested on `x86_64-linux`. But actually nixd may work on other platforms (e.g. `aarch64-linux`).

If you have tested this please update the flake (if it works), or submit an issue (oops...).

**Comment by 573** [comment]
I think it should be safe to update the flake at least I managed to cross-compile `nixd` in a devShell:

>$ nix develop .#devShells.aarch64-linux.nixd --override-input nixd "../nixd" --command bash -c "pushd ~/nixd && file build/nixd && git diff --cached"
warning: Git tree '/home/dkahlenberg/.nix-config' is dirty
warning: Git tree '/home/dkahlenberg/nixd' is dirty
warning: not writing modified lock file of flake 'git+file:///home/dkahlenberg/.nix-config':
• Updated input 'nixd':
    'github:nix-community/nixd/5bf24a323345a61ef8365f81205623f5b3addf56' (2023-05-30)
  → 'git+file:///home/dkahlenberg/nixd' (2023-05-30)
~/nixd ~/.nix-config
build/nixd: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /nix/store/c307jrr61k4a20hrvmrp3v6if83wk10d-glibc-2.37-8/lib/ld-linux-aarch64.so.1, for GNU/Linux 3.10.0, not stripped
diff --git a/flake.nix b/flake.nix

```diff
index c11c555..809acb8 100644
--- a/flake.nix
+++ b/flake.nix
@@ -45,6 +45,6 @@
           '';
         };
       };
-    systems = [ "x86_64-linux" ];
+    systems = [ "x86_64-linux" "aarch64-linux" ];
   };
 }
```

**Comment by adisbladis** [comment]
This is partially dealt with in #41.

**Comment by inclyc** [comment]
Tested that `nixd` works on `aarch64-linux` (Apple M1), and Raspberry Pi

**Comment by inclyc** [comment]
> Tested that `nixd` works on `aarch64-linux` (Apple M1), and Raspberry Pi

Sadly tests fail on M1.

**Comment by inclyc** [comment]
> > Tested that `nixd` works on `aarch64-linux` (Apple M1), and Raspberry Pi
> 
> Sadly tests fail on M1.

fallback to single-thread mode, to workaround our eval tasks. #45

**Comment by inclyc** [comment]
#53

**Comment by inclyc** [comment]
Regression tests & unit tests SIGESGV on darwin
