### ISSUE TITLE
[feature] goto definition cannot work for inherit

### ISSUE THREAD

**Issue by Freed-Wu** [nix-community/nixd#361]
```nix
  pname = "spglib";
  version = "2.1.0";
  format = "pyproject";

  src = fetchPypi {
    inherit pname version;
    hash = "sha256-gUNUX9/8EfvNpNcFpra81Iid6bw1JLeN+GajbdDeCks=";
  };
```

When cursor is in `inherit pname`'s `pname`, press goto definition cannot jump to `pname = "spglib";`'s `pname`.

**Comment by inclyc** [comment]
Nixd is under a massive rewriting and the new def-use framwork is WIP, legacy nixd codes is not maintained (EOL).
