### ISSUE TITLE
[Noob] How do I get the latest git verson declaratively?

### ISSUE THREAD

**Issue by Ciel-MC** [nix-community/nixd#369]
I tried importing the flake and installing the nixd package but it didn't seem to do anything. Or do I have to manually clone and install the repo?

**Comment by higherorderfunctor** [comment]
@Ciel-MC, also a noob, but this is how I do it so I can just install with `home.packages = [pkgs.nixd];` using Home Manager (same with or without the overlay).  This replaces the package in nixpkgs with the latest version.

I have a growing list of overlays, so I've been organizing them in their own directory.  Running `nix flake update` will update to the latest commit.  You can simplify this to all be flake.nix if you wanted.

flake.nix
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    ...
    nixd = { -- the input tracking this repo
      url = "github:nix-community/nixd";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    ...
  };
  outputs = {
    self,
    nixpkgs,
    home-manager,
    ...
  } @ inputs: let
    # most of this is borrowed from https://github.com/Misterio77/nix-config
    inherit (self) outputs;
    lib = nixpkgs.lib // home-manager.lib;
    systems = ["x86_64-linux" "aarch64-linux"];
    forAllSystems = f: lib.genAttrs systems (system: f pkgsFor.${system});
    pkgsFor = lib.genAttrs systems (system:
      import nixpkgs {
        inherit system;
        config.allowUnfree = true;
        # imports all my overlays
        overlays = import ./overlays/default.nix {inherit inputs;};
      });
  in {
    ...
    nixosConfigurations = {
      myNixosConfig = lib.nixosSystem {
        modules = [./path/to];
        specialArgs = {inherit inputs outputs;};
        pkgs = pkgsFor.x86_64-linux;  # passes nixpkgs with the overlays applied
      };
      ...
    };
    # HM only systems
    homeConfigurations = {
      myHomeManagerConfig = lib.homeManagerConfiguration {
        modules = [./path/to];
        extraSpecialArgs = {inherit inputs outputs;};
        pkgs = pkgsFor.x86_64-linux;  # passes nixpkgs with the overlays applied
      };
      ...
    };
  };
}
```

overlays/default.nix
```nix
{inputs, ...}: [
  (import ./nixd-overlay.nix {inherit inputs;}) # imports this specific overlay
  ...
]
```

overlays/nixd-overlay.nix
```nix
{inputs, ...}: inputs.nixd.overlays.default # applies the overlay
```

**Comment by inclyc** [comment]
> I tried importing the flake and installing the nixd package but it didn't seem to do anything. Or do I have to manually clone and install the repo?

Nixpkgs version is the latest release, the main branch here is working in progress and not stable.

**Comment by Ciel-MC** [comment]
> > I tried importing the flake and installing the nixd package but it didn't seem to do anything. Or do I have to manually clone and install the repo?
> 
> Nixpkgs version is the latest release, the main branch here is working in progress and not stable. Please just use nixpkgs version, e.g. `with pkgs; [ nixd ]` .
> 
> Hi @higherorderfunctor I would like to hide your comment here because I think current main branch is not ready for production yet...

Hello, so if I understand it correctly, you are under no circumstances supposed to use the main branch? Even if breakage is to be expected? Unlike how Nvim nightly can still expect some degree of stability, it could be completely broken on a commit, is that correct?

**Comment by inclyc** [comment]
> Hello, so if I understand it correctly, you are under no circumstances supposed to use the main branch? Even if breakage is to be expected? Unlike how Nvim nightly can still expect some degree of stability, it could be completely broken on a commit, is that correct?

Yes.

>  Even if breakage is to be expected? 

This is not "breakage", main branch is basically NOT working for now.
