### ISSUE TITLE
nixd-attrset-eval running after closing nvim

### ISSUE THREAD

**Issue by matejc** [nix-community/nixd#436]
Reproducable by:

- open nvim
- open nix file
- save nix file
- :qall
- process appears with 100% cpu usage in htop

![image](https://github.com/nix-community/nixd/assets/854770/0326e989-6fc2-43f2-bec9-a493765c5892)

This is on nixd-nightly.

**Comment by inclyc** [comment]
> This is on nixd-nightly.

Are there any coredumps? 

`nixd-attrset-eval` should have notified by `nixd` process , if it exits elegantly.

**Comment by inclyc** [comment]
If you don't know why please `pkill -9` it. Killing eval process currently does not leave anything dirty on your system.

**Comment by inclyc** [comment]
> Are there any coredumps?

Run command `coredumpctl`, see last a few items in that list.



> open nix file

What't the content of that nix file?

**Comment by matejc** [comment]
> > Are there any coredumps?
> 
> Run command `coredumpctl`, see last a few items in that list.

Last one if from 2 days ago and is unrelated to this, so nothing today 

> > open nix file
> 
> What't the content of that nix file?

Save any nix file (tested with cloned nixpkgs)

**Comment by matejc** [comment]
logs ~/.local/state/nvim/lsp.log
```
[ERROR][2024-04-19 10:56:51] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:56:51.091] 190442: <-- shutdown(6)\nI[10:56:51.095] 190442: --> notify exit\n"
[START][2024-04-19 10:57:00] LSP logging initiated
[ERROR][2024-04-19 10:57:00] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:00.772] 191456: <-- initialize(1)\nI[10:57:00.772] 191456: --> reply:initialize(1)\nI[10:57:00.773] 191456: --> call window/workDoneProgress/create(1)\nI[10:57:00.773] 191456: --> notify $/progress\nI[10:57:00.773] 191456: --> call attrset/evalExpr(1)\nI[10:57:00.774] 191456: --> call window/workDoneProgress/create(2)\nI[10:57:00.774] 191456: --> notify $/progress\nI[10:57:00.774] 191456: --> call attrset/evalExpr(1)\nI[10:57:00.774] 191456: --> call workspace/configuration(3)\n"
[ERROR][2024-04-19 10:57:00] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:00.859] 191456: <-- initialized\n"
[ERROR][2024-04-19 10:57:00] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:00.864] 191456: <-- textDocument/didOpen\n"
[ERROR][2024-04-19 10:57:00] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:00.869] 191456: --> notify textDocument/publishDiagnostics\nI[10:57:00.870] 191456: <-- textDocument/documentSymbol(2)\nI[10:57:00.870] 191456: <-- reply(1)\nI[10:57:00.870] 191456: <-- reply(2)\nI[10:57:00.870] 191456: <-- reply(3)\nI[10:57:00.870] 191456: <-- textDocument/semanticTokens/full(3)\nE[10:57:00.870] 191456: workspace/configuration: parse error expected object\nI[10:57:00.871] 191456: --> reply:textDocument/semanticTokens/full(3)\n"
[ERROR][2024-04-19 10:57:00] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:00.892] 191456: --> reply:textDocument/documentSymbol(2)\n"
[ERROR][2024-04-19 10:57:01] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:01.114] 191456: <-- reply(1)\nI[10:57:01.114] 191456: --> notify $/progress\n"
[ERROR][2024-04-19 10:57:01] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:01.267] 191456: <-- textDocument/documentHighlight(4)\nI[10:57:01.267] 191456: --> reply:textDocument/documentHighlight(4)\nE[10:57:01.267] 191456: textDocument/documentHighlight failed: Cannot find definition of this node\n"
[ERROR][2024-04-19 10:57:01] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:01.821] 191456: <-- reply(1)\nI[10:57:01.821] 191456: --> notify $/progress\n"
[ERROR][2024-04-19 10:57:10] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:10.896] 191456: <-- textDocument/didSave\nI[10:57:10.896] 191456: unhandled notification textDocument/didSave\n"
[ERROR][2024-04-19 10:57:11] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:11.306] 191456: <-- textDocument/documentHighlight(5)\nI[10:57:11.306] 191456: --> reply:textDocument/documentHighlight(5)\nE[10:57:11.306] 191456: textDocument/documentHighlight failed: Cannot find definition of this node\n"
[ERROR][2024-04-19 10:57:13] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/wr95hgppfna32ld2acbrnrbmfvlsm21c-nixd-nightly/bin/nixd"	"stderr"	"I[10:57:13.319] 191456: <-- shutdown(6)\nI[10:57:13.321] 191456: --> notify exit\n"
```

**Comment by inclyc** [comment]
[Screencast_20240419_160354.webm](https://github.com/nix-community/nixd/assets/36667224/a02fb2ca-a00b-45d5-b6d3-6fc971947890)

**Comment by inclyc** [comment]
In my environment they exited cleanly?

**Comment by matejc** [comment]
> Is nvim killing nixd process preventing it sending another notification?

That could be the case, since sometimes after exiting vim I have 3 left and sometimes 2. But always just one has 100% cpu. Another thing, when I kill any one, all of them disappear.

While running:
![image](https://github.com/nix-community/nixd/assets/854770/90cbe62c-5fc5-4208-b4fc-ef5805b58b0e)
After quit:
![image](https://github.com/nix-community/nixd/assets/854770/b623937f-0972-4e6d-8551-4efb737740d5)

**Comment by inclyc** [comment]
Also, could you please try current main branch?

**Comment by matejc** [comment]
I used current main from few hours ago. And just tried 7b339bc147f54d34410b8f9a54d93c66846c28ee (now current main). Still the same issue.

**Comment by inclyc** [comment]
How about our testing environment then?

```
$ nix develop github:nix-community/nixd#vscodium

$ codium-test
```

**Comment by inclyc** [comment]
Could you please launch this in your workspace and see if it is a vim issue?

**Comment by inclyc** [comment]
I just test nvim setup in my workspace it seems to reproduce the same result.

**Comment by matejc** [comment]
vscodium works as expected - no leftover processes
I just integrated nixd-nightly into helix editor (to try it out in some other editor) and it also works flawlessly
just nvim leaves these processes

**Comment by inclyc** [comment]
Test the branch  #437 ?

**Comment by inclyc** [comment]
Tried:
 
```
nix develop 'github:nix-community/nixd?rev=d825f45b09e08bd56f31991906fb9592c4fdbb85#nvim'
```

No process left then.

**Comment by matejc** [comment]
Great job! That seems to fix it

**Comment by DockterTeagle** [comment]
I am having this issue now as well and I dont know why? I am using the flake for nixd as well

**Comment by DockterTeagle** [comment]
I am also having an issue where it takes forever to evaluete options, here is my most recent lsp-log.txt:
[lsp.log](https://github.com/user-attachments/files/18284503/lsp.log)

**Comment by leon-erd** [comment]
I have the same in vscode. nixd-attrset-eval keeps running after closing vscode and it takes forever to evaluate the options

**Comment by inclyc** [comment]
> I have the same in vscode. nixd-attrset-eval keeps running after closing vscode and it takes forever to evaluate the options

Can you provide additional context about the problem? Checklist:

- LSP log
- `nixd --version`
- The configuration.

**Comment by leon-erd** [comment]
Hey! Thanks for the fast response. After reading through the logs (Im not sure if they are the nixd logs or the nix-ide vscode extension logs) I managed to find the error.
The problem was that I didnt use this syntax with the quotation marks to escape the "@" symbol
```json
"home-manager": {
      "expr": "(builtins.getFlake \"/home/lyc/flakes\").homeConfigurations.\"lyc@adrastea\".options"
    }
```
Therefore the home-manager options could not be read successfully and apparently this caused nixd to get stuck. This disabled the loading of any options (also nixos options) for me and caused `nixd-attrset-eval` to not close after exiting vscode.
I think it would be nice if (in the case of an error getting some options) nixd would just ignore this and proceed as if the expr was not set.
