### ISSUE TITLE
Jump to definition of custom modules

### ISSUE THREAD

**Issue by Atemu** [nix-community/nixd#451]
Jumping to the definition of NixOS' options works great apart from missing submodule support (https://github.com/nix-community/nixd/issues/106).

My config contains lots of custom options that I use everywhere though. It'd be great if I could jump to those aswell.

**Comment by inclyc** [comment]
> In https://github.com/nix-community/nixd/issues/451 I can see you would like to get completions for your custom module. Then you need such config.

Exactly, set this `options` section, and modify the "expr" to eval. By default it reads from `<nixpkgs>` thus there is no "custom" modules.

https://github.com/nix-community/nixd/blob/a8d7322d35dce8c0d6a54eb24213cfe31f5339d3/nixd/docs/editors/nvim-lsp.nix#L375

You can set to your flake as well. (Also a PR for improving docs are appreciated!)

**Comment by inclyc** [comment]
> My config contains lots of custom options that I use everywhere though. It'd be great if I could jump to those aswell.

Note that this is already implemented, thus you only need to write some simple config stuff. (Like above).

Generally I hate any config effort so maybe there will be a "pop-up" window saying that if you are using a flake, then the default options set will be evaluated from the flake. (Thus nixd works out of box again).

**Comment by inclyc** [comment]
Closing as this has already being landed.

**Comment by Atemu** [comment]
Thank you very much for the reply!

I don't use flakes but I do have a default.nix which exports my hosts as attributes. I have set the expr for nixos to `<hostname>.options` (which you could instantiate via `nix-instantiate --eval -A <hostname>.options`) but I still can't jump to definitions. What am I doing wrong?

**Comment by Atemu** [comment]
> Also a PR for improving docs are appreciated

To write docs, you must first have knowledge; it's a bootstrapping problem ;)

**Comment by Atemu** [comment]
Hold on, I may have done it. At least in the example nvim config, not in my emacs yet.

Could it be that nixd calls the project's default.nix with some arguments? I use a terrible hack to make my default.nix function as either a nixos module or a default.nix for nix-build by checking whether any args are passed (nix-build does not pass any, nixos modules get passed the specialArgs).

**Comment by inclyc** [comment]
> Could it be that nixd calls the project's default.nix with some arguments?

Literally you can write arbitrary expression in that field. It is evaluated by "real" C++ nix evaluator. (Including builtins).

Specifically, for your use case you can do:

```nix
import ./default.nix ... # arguments to pass
```

**Comment by Atemu** [comment]
Oh yeah, that's how I got it to work ;)

    (import ./default.nix { }).<hostname>.options

On that topic, what is `./` relative to? The project root? I'm asking because the example config provides an absolute path to `getFlake`.

**Comment by inclyc** [comment]
> The project root? 

Yes.

> I'm asking because the example config provides an absolute path

That's C++ nix limitation.

```
nix-repl> builtins.getFlake "."
error:
       … while calling the 'getFlake' builtin
         at «string»:1:1:
            1| builtins.getFlake "."
             | ^

       error: flake reference '.' is not an absolute path

```
