### ISSUE TITLE
Documentation on .nixd.json unclear/out of date?

### ISSUE THREAD

**Issue by Atemu** [nix-community/nixd#452]
The [current documentation of the config file](https://github.com/nix-community/nixd/blob/a8d7322d35dce8c0d6a54eb24213cfe31f5339d3/nixd/docs/user-guide.md#L86) is rather short on details; providing only an annotated example config.

Is this config file still effective and/or necessary however? With the newest version, `nixd` appears to work fine without any config whatsoever. When do I need such a config file? This fact is not reflected in the documentation.

The docs are also missing basic explanations such as what the file needs to be named (is it still `.nixd.json`?) or where it needs to/can be placed.

**Comment by inclyc** [comment]
> Is this config file still effective and/or necessary however?

Yes. This is newest nixd configuration.

> When do I need such a config file?

In #451 I can see you would like to get completions for your custom module. Then you need such config.

> This fact is not reflected in the documentation.

Yes, there are too many things to do in this repo (lack lab force)? 

> The docs are also missing basic explanations such as what the file needs to be named

Yes. This should be addressed by https://github.com/nix-community/nixd/issues/447

Configurations are now written in standard `workspace/configuration` requests. Thus the location is different among editors. AFAIK for vscode users the configuration should be written to `settings.json`, I provided some examples in the vscode-nix-ide extension README.

https://github.com/nix-community/vscode-nix-ide/tree/main#language-servers


For nvim users,  it should be placed at `nixd.setup{}` section. For example https://github.com/nix-community/nixd/blob/a8d7322d35dce8c0d6a54eb24213cfe31f5339d3/nixd/docs/editors/nvim-lsp.nix#L362
