### ISSUE TITLE
docs: update json-schema

### ISSUE THREAD

**Issue by inclyc** [nix-community/nixd#454]
@Freed-Wu 

Legacy `.nixd.json` is outdated, would you like to update the schema? (Currently it is based on `workspace/configuration`)

**Comment by Freed-Wu** [comment]
I haven't figure out what is [workspace/configuration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) let me digest it :)

**Comment by inclyc** [comment]
Yes , that's our missing doc in #447

**Comment by inclyc** [comment]
See https://github.com/nix-community/nixd/issues/452#issuecomment-2073884509 for brief explaination.

**Comment by Freed-Wu** [comment]
It looks like workspace/configuration puts settings to `settings.json`. So original json schema for `.nixd.json` have been deprecated.

**Comment by inclyc** [comment]
> It looks like workspace/configuration puts settings to [settings.json](https://github.com/nix-community/vscode-nix-ide/blob/main/package.json#L96).

Do you think we should write a new schema for `settings.json` somehow?

**Comment by Freed-Wu** [comment]
https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema

`package.json`'s `contributes.configuration` also be a json schema format. The patch should belong to https://github.com/nix-community/vscode-nix-ide .

**Comment by inclyc** [comment]
Thanks, closing then
