### ISSUE TITLE
sema-escaping-with highlighting too much

### ISSUE THREAD

**Issue by jhillyerd** [nix-community/nixd#475]
I'm finding most of all my nix files triggering

```
DIAG("sema-escaping-with", EscapingWith, Warning,
     "this variable will escape nested `with`, binding to static name")
```

1. Highlighting the entire with expression is not helpful/very noisy.  Not sure if it's possible with LSP just to highlight the `with ... ;` part?
2. It's not clear how to resolve this warning, and I *think* in many cases I want the value to escape.  ie, in the snippet below I definitely want my let bound neovim and vim-is-neovim to override the with pkg attrs.

![image](https://github.com/nix-community/nixd/assets/2502736/db00ef5e-34ae-45ce-88ef-6a35bff560c4)

**Comment by inclyc** [comment]
> 1. Highlighting the entire with expression is not helpful/very noisy.  Not sure if it's possible with LSP just to highlight the `with ... ;` part?

 I believe this is a rendering issue, for some editors it just shows at the `with` keyword. I can reduce the range also.

> It's not clear how to resolve this warning, and I *think* in many cases I want the value to escape.  ie, in the snippet below I definitely want my let bound neovim and vim-is-neovim to override the with pkg attrs.

This is somehow an anti-pattern in nix language. I would like to suggest using `++` operator to resolve add "neovim" and vim-is-neovim separately, not in the `with`-ed list. 

Read https://github.com/NixOS/nix/issues/490 for more details.

**Comment by jhillyerd** [comment]
Perhaps you could leverage the GitHub wiki feature so that there is a landing page for each of the warnings, with information similar to what you posted.  The community could then refine, add examples etc.

It took me several tries to even find the source code with the comment that explained what was meant by escaping in this content.

**Comment by inclyc** [comment]
Perhaps you could leverage the GitHub wiki feature so that there is a landing page for each of the warnings, with information similar to what you posted. The community could then refine, add examples etc.

It took me several tries to even find the source code with the comment that explained what was meant by escaping in this context.

 Thanks for suggestion, I'll add the links!

**Comment by spikespaz** [comment]
I want to turn this of, I have a different opinion. I am aware of how scoping of `with` works.

**Comment by inclyc** [comment]
> I want to turn this off, I have a different opinion. I am aware of how scoping of `with` works.

Yes, we have a plan to make all diagnostics toggleable, I recently have no bandwidth to do it. See #477.
