### ISSUE TITLE
Wrong error on last arguemnt ending with a comma

### ISSUE THREAD

**Issue by Libadoxon** [nix-community/nixd#479]
[nixfmt](https://github.com/NixOS/nixfmt) formats expression arguments to end with a commma for [diff reasons](https://piegames.de/dumps/leading-commas/#the-issue). Nixd however displays a wrong "empty formal" error when the last argument ends with a comma.
![image](https://github.com/nix-community/nixd/assets/90480641/e6e69b90-32ae-4386-a372-55787a13bd59)

**Comment by inclyc** [comment]
I can downgrade this 'error' to a warning.

As per my understanding for the formatting RFC. formal commas should always be placed in the front. That's *correct* formatting.

**Comment by inclyc** [comment]
Ah, I just read the links carefully. I'm convinced to accept this.
