### ISSUE TITLE
Variable gets declared as unused when used with an @ symbol

### ISSUE THREAD

**Issue by Libadoxon** [nix-community/nixd#487]
![image](https://github.com/nix-community/nixd/assets/90480641/a2eb4f37-e432-475b-aa03-4499e5cbc0ff)

**Comment by inclyc** [comment]
Apparently you did not use `foo` in this case. What's the bug?

**Comment by Libadoxon** [comment]
I don't quite understand your reply. In my example I use `foo` through `args`, `foo` is set to `out`. If I remove `args.` before `foo` I don't get this warning.

**Comment by inclyc** [comment]
> In my example I use `foo` through `args`, `foo` is set to `out`.

There is no such "use" through `args`. In nix language literally you used `args`, and select the `args` attribute set via the name `foo`.

In this code example you can write

```nix
{ ... }@args : { out = args.foo; }
```

**Comment by Libadoxon** [comment]
Thx for the explanation, this is now more clear to my.
