### ISSUE TITLE
real world example

### ISSUE THREAD

**Issue by adrian-gierakowski** [nix-community/nixd#492]
hi

Thanks for this great project!

Would it be possible to provide a more realistic example, with nix code split across multiple files and how to configure nixd for nixpkgs and options completions to work in files other than `flake.nix`? For example, if I do something like the following in `flake.nix`

```nix
  my-package = pkgs.callPackgea ./my-package.nix {};
```

and then in `my-package.nix`: 

```nix
{ pkgs, stdenv }: {
   ...
}
```

is it possible to get completions for arguments or attrs of `pkgs` in `my-package.nix`? 

Thanks!

**Comment by inclyc** [comment]
> Would it be possible to provide a more realistic example, with nix code split across multiple files and how to configure nixd for nixpkgs and options completions to work in files other than flake.nix? 

It shall work out of box for "other files". Have you tried?

> is it possible to get completions for arguments or attrs 

No.

**Comment by adrian-gierakowski** [comment]
> It shall work out of box for "other files". Have you tried?

yes, but it seems like what I was expecting doesn't event work inside `flake.nix` or `default.nix`, for example in:

```nix
let
  pkgs = import <nixpkgs> {};
in
  pkgs.
```

I was expecting to get completions for `pkgs.`

> No. The completion merely works for some idioms in nix language. Not generally deal the outside - given attributes.

aha, I guess that's why it looked like things didn't work, I just didn't know what should be expected to work

now I see that completions work for packages in this example:

```nix
let
  pkgs = import <nixpkgs> {};
in
  with pkgs; [
     # completions work here!
  ]
```

but not if I rename `pkgs` to something else:

```nix
let
  pkgs-unstable = import <nixpkgs> {};
in
  with pkgs-unstable; [
     # completions do not work here!
  ]
```

are supported "idioms" I documented anywhere? Thanks!

**Comment by inclyc** [comment]
> are supported "idioms" I documented anywhere? Thanks!

No. These are currently unstable for users, thus it is not documented. I think maybe I would like to *support* `pkgs-unstable` completions in the furture, rather than documenting some idioms.

**Comment by inclyc** [comment]
In fact I'm working on https://github.com/nix-community/nixd/issues/482 to satisfy users' requests like this one. It is on *design-review* state currently, needs sometime for implementation. You can discuss some idea/details there, if you would like to help.
