### ISSUE TITLE
example of usage and configuration without flakes

### ISSUE THREAD

**Issue by adrian-gierakowski** [nix-community/nixd#493]
would be great to have an example for people who haven't switched to flakes yet

**Comment by inclyc** [comment]
Note the configuration doc explicitly said you don't need to do anything if you are not using flake.

**Comment by adrian-gierakowski** [comment]
how I arrived here:

1. I saw an flake based example, tested it locally, and saw some things working
2. then I tried to use nixd on an existing project and things I expected to work didn't work (see more [here](https://github.com/nix-community/nixd/issues/492#issuecomment-2098499219)) so I assumed there was something special about how flakes are handled 

but it turns out that my metal model of how nixd works was incorrect

I thing it would be great to better document [existing features ](https://github.com/nix-community/nixd/blob/main/nixd/docs/features.md) to set the right expectations 

Thanks!
