### ISSUE TITLE
document nixf-tidy

### ISSUE THREAD

**Issue by mightyiam** [nix-community/nixd#497]
Thank you for nixd and nixf-tidy.

I want to use nixf-tidy to lint my project, both locally and in GitHub Actions.

But I couldn't find any documentation for this.

Running the nixf-tidy command seems to run a process that never exits and does not provide output.

I did find the https://github.com/inclyc/nixf-tidy-action repo, but it is not via a GitHub Action that I would like to use it.

**Comment by inclyc** [comment]
> Running the nixf-tidy command seems to run a process that never exits and does not provide output.

For now it reads the standard input as the source file. You may use it like:

```
cat somefile.nix | nixf-tidy
```

**Comment by mightyiam** [comment]
Thank you!
