### ISSUE TITLE
nixd dies on shutdown but not in the way eglot expects?

### ISSUE THREAD

**Issue by Atemu** [nix-community/nixd#499]
Whenever I shutdown `nixd` via emacs' eglot either via `eglot-shutdown` or by killing the last buffer, eglot complains that the LSP died:

```
(jsonrpc-error "request id=15 failed:" (jsonrpc-error-code . -1) (jsonrpc-error-message . "Server died") (jsonrpc-error-data))
```

Well, of course it died (that's what it's supposed to do) but somehow it doesn't shut down like eglot expects it to?

`haskell-language-server` exits properly from eglot's perspective, so it must be something about nixd.

Here's `nixd --log=debug` stderr from the point I stop it:

```
V[15:06:47.125] 249743: <<< {"jsonrpc":"2.0","id":4,"method":"shutdown","params":null}
I[15:06:47.125] 249743: <-- shutdown(4)
I[15:06:47.126] 249743: --> notify exit
V[15:06:47.126] 249743: >>> {"jsonrpc":"2.0","method":"exit","params":null}
I[15:06:47.158] 249743: --> notify exit
V[15:06:47.158] 249743: >>> {"jsonrpc":"2.0","method":"exit","params":null}
```

Eglot's event buffer I captured in another repro:

```
(:jsonrpc "2.0" :id 5 :method "shutdown" :params nil)
[stderr] V[17:53:05.692] 257822: <<< {"jsonrpc":"2.0","id":5,"method":"shutdown","params":null}
[stderr] I[17:53:05.692] 257822: <-- shutdown(5)
[stderr] I[17:53:05.696] 257822: --> notify exit
[stderr] V[17:53:05.696] 257822: >>> {"jsonrpc":"2.0","method":"exit","params":null}
[stderr] I[17:53:05.731] 257822: --> notify exit
[stderr] V[17:53:05.731] 257822: >>> {"jsonrpc":"2.0","method":"exit","params":null}
[internal] Fri May 17 17:53:05 2024:
(:message "Connection state changed" :change "finished\n")

----------b---y---e---b---y---e----------
```

What I find weird is the two exit calls but I'm not familiar with the LSP.

```
nixd, version: 2.1.2
```

**Comment by inclyc** [comment]
There are merely two problems reported in this issue, the first:

> I[15:06:47.126] 249743: --> notify exit
> V[15:06:47.126] 249743: >>> {"jsonrpc":"2.0","method":"exit","params":null}
> I[15:06:47.158] 249743: --> notify exit
> V[15:06:47.158] 249743: >>> {"jsonrpc":"2.0","method":"exit","params":null}

These two "exit" requests is sent by our server to eval providers (one for nixpkgs, another for an options system) and are **expected**. And I dedicated wrote these requests in the source code, to make the workers clean the resources.

In nixd, these eval providers are used for interoperating with C++ nix, these workers directly links with C++ nix libraries, effectively the `nix-repl` exposed by an RPC protocol. 


the second:

>  eglot complains that the LSP died:

I don't know what's the reason exactly, if it does not bother you, can we leave this as-is?

**Comment by Atemu** [comment]
> if it does not bother you, can we leave this as-is?

The problem is that the server not shutting down "cleanly" has knock-on effects. Eglot has a function to shutdown the server when the last LSP-managed buffer of a project is killed. When the server doesn't shut down cleanly, it (rightfully) complains and aborts killing the buffer which is annoying to deal with; especially when killing multiple projects at once.

I am not familiar with the LSP spec in the slightest. Since you are, do you have a hunch what might be going wrong here?

Is there any way to get more debug info from the nixd side?
