### ISSUE TITLE
unnecessary  "definition is not used warning"

### ISSUE THREAD

**Issue by sachinchaudhary1808** [nix-community/nixd#500]
so i have a flake.nix in which i have some variable and i have imported it to like home.nix file and when i add then into top like {config, pkgs, inputs, userSettings, ...) and i use them nixd still gives me a warning that userSettings is not used but it's being used...

here is the screenshot..
![image](https://github.com/nix-community/nixd/assets/138745629/461811e2-a10d-47b8-9575-ac6e17db1f16)

**Comment by inclyc** [comment]
Please paste the code here, for example

```nix
{
   # your nix code
}
```

**Comment by inclyc** [comment]
I see, it is indeed a bug, you can workaround it by deleting the empty `let ... in ..` in your file.

**Comment by inclyc** [comment]
I think the code should not exit early here:

https://github.com/nix-community/nixd/blob/51adffb162b3fce43b92808599b1ef6891483108/libnixf/src/Sema/VariableLookup.cpp#L223C1-L224C12
