### ISSUE TITLE
[bug] nixd uses too much RAM when opening large files

### ISSUE THREAD

**Issue by JohnRTitor** [nix-community/nixd#504]
I use `nixd` (2.1.2 from nixpkgs) configured via `nix-ide` vscode extension.

If I open a file with large no of expressions like the `pkgs/top-level/all-packages.nix` on nixpkgs, the whole system becomes very slow, with CPU usage topping 100%! Memory usage is around 10Gigs as seen from `btop`.

I am on a DDR5 5200 16GB system, but this bug is very problematic leading to OOM.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.0-cachyos, NixOS, 24.05 (Uakari), 24.05.20240515.33d1e75`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.22.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/0qd773b63yg8435w8hpm13zqz7iipcbs-source`
```

**Comment by inclyc** [comment]
Known issue, this is caused by large document symbols as per my profiling data.

**Comment by inclyc** [comment]
Duplicated to #462
