### ISSUE TITLE
Complete outputs: (dev out) for `package_name.`

### ISSUE THREAD

**Issue by Freed-Wu** [nix-community/nixd#509]
**Is your feature request related to a problem? Please describe.**
![Screenshot from 2024-05-24 16-52-28](https://github.com/nix-community/nixd/assets/32936898/b53f316b-c8b7-4165-90f2-4825a782e65b)

When user press `.` after a package, complete `.out`, `.dev`, ...

For example, `girara` should have `.dev` and `.out`.

**Describe the solution you'd like**

TIA!

**Comment by inclyc** [comment]
Derivations usually has many attributes, not only .out or .dev
