### ISSUE TITLE
Wrong suggestions for rec keyword.

### ISSUE THREAD

**Issue by voronind-com** [nix-community/nixd#513]
**Describe the bug**
I've got an example where `rec` is actually required, but nixd suggests to remove it.

**Logs (Required)**
[Here](https://git.voronind.com/voronind/nixos/src/commit/82ee67bb358cd58a135af3361994b9b6709f5d90/overlay/Keyd.nix) is an overlay that I made for Keyd.

**To Reproduce**
Check my Nix example.

**Expected behavior**
Nixd sees the `inherit patches` and does not suggest the removal.

**Screenshots**
![image](https://github.com/nix-community/nixd/assets/22127600/ad99ad48-15dc-471c-b9b7-8fbc20a6a8e6)

**Comment by inclyc** [comment]
Yes, looks like indeed a bug.

**Comment by inclyc** [comment]
```nix
rec {
  a = 1;
  b = rec {
    inherit a;
  };
}
```
