### ISSUE TITLE
support & auto complete nixvim options

### ISSUE THREAD

**Issue by inclyc** [nix-community/nixd#517]
Write documentation & serious testing about nixvim modules. It is a nice module system we'd like to cover.

**Comment by inclyc** [comment]
```nix
    programs.nixvim = mkOption {
      default = { };
      type = types.submoduleWith {
        shorthandOnlyDefinesConfig = true;
        specialArgs = {
          hmConfig = config;
          inherit helpers;
        };
        modules = [ (import ./modules/hm.nix { inherit lib; }) ] ++ shared.topLevelModules;
      };
    };
```

currently all nixvim options are nested under "submodules". We have basic support for things like `attrsOf (submoules)` but the options completion stops at `programs.nixvim` so thus it cannot complete the rest.

CC @GaetanLepage

This is a funny case exists in real world, and I think it is mandatory to support it. Let's mark this issue an enhancement for this specific types.

**Comment by GaetanLepage** [comment]
> ```nix
>     programs.nixvim = mkOption {
>       default = { };
>       type = types.submoduleWith {
>         shorthandOnlyDefinesConfig = true;
>         specialArgs = {
>           hmConfig = config;
>           inherit helpers;
>         };
>         modules = [ (import ./modules/hm.nix { inherit lib; }) ] ++ shared.topLevelModules;
>       };
>     };
> ```

Where is this snippet coming from ? Nixvim codebase ?

Anyway, thanks for your efforts in including Nixvim support in nixd !

**Comment by inclyc** [comment]
> Where is this snippet coming from ? Nixvim codebase ?

https://github.com/nix-community/nixvim/blob/d15fade62b743839a20d927d3506d503858f49f0/wrappers/hm.nix#L30

**Comment by inclyc** [comment]
The documentation part see #520
