### ISSUE TITLE
Warning suppression is ignored, warnings are still shown

### ISSUE THREAD

**Issue by novo-max** [nix-community/nixd#525]
**Describe the bug**

Option to ignore warnings has no effect.

**Configuration**

```
{
    "nix.enableLanguageServer": true,
    "nix.serverPath": "nixd",
    "nix.serverSettings": {
        "nixd": {
            "formatting": {
                "command": [
                    "nixpkgs-fmt"
                ]
            },
            "diagnostic": {
                "suppress": [
                    "sema-def-not-used"
                ]
            }
        }
    }
}
```

**To Reproduce**

1. Install VSCodium
2. Install extension jnoortheen.nix-ide
3. Apply configuration
4. Open *.nix file with unused bindings.

**Expected behavior**
Warnings should not be displayed

**Screenshots**
![image](https://github.com/nix-community/nixd/assets/172879703/fa87e447-5912-4049-8b9e-e0eae8195259)

**Additional context**
Tested in the most current version of NixOS.

Discussed here: https://discourse.nixos.org/t/nixd-nix-language-server/28910/42

**Comment by inclyc** [comment]
> Tested in the most current version of NixOS.

It is introduced in 2.2.0, check your version?

**Comment by novo-max** [comment]
I tested it both with version 2.1.2 and 2.2.0 - same behavior for both. My current version is

```
nixd --version
nixd, version: 2.2.0
```

**Comment by novo-max** [comment]
I changed it since but you can use this one:

```
{
  inputs = {
    openwrt-imagebuilder.url = "github:astro/nix-openwrt-imagebuilder";
  };
  outputs = { self, nixpkgs, openwrt-imagebuilder }: {
    packages.x86_64-linux.my-router =
      let
        pkgs = nixpkgs.legacyPackages.x86_64-linux;

        profiles = openwrt-imagebuilder.lib.profiles { inherit pkgs; };

        config = profiles.identifyProfile "avm_fritz7412" // {
          # add package to include in the image, ie. packages that you don't
          # want to install manually later
          packages = [ "tcpdump" ];

          disabledServices = [ "dnsmasq" ];

          # include files in the images.
          # to set UCI configuration, create a uci-defauts scripts as per
          # official OpenWRT ImageBuilder recommendation.
          files = pkgs.runCommand "image-files" {} ''
            mkdir -p $out/etc/uci-defaults
            cat > $out/etc/uci-defaults/99-custom <<EOF
            uci -q batch << EOI
            set system.@system[0].hostname='testap'
            commit
            EOI
            EOF
          '';
        };

      in
        openwrt-imagebuilder.lib.build config;
  };
}
```
from: https://github.com/astro/nix-openwrt-imagebuilder

![image](https://github.com/nix-community/nixd/assets/172879703/ea9b8aa6-5642-48f8-8bdc-ffa4e4c5bb4b)

**Comment by inclyc** [comment]
Cannot reproduce. It works pretty well as expected on my machine.

How about changing the `nix.serverPath` to absolute path pointing to nixd 2.2.0 ? I think there may be some launching issue about the version you used. If the issue still occurs, please  `export NIXD_FLAGS=-log=verbose`, lauch vscode again, and paste the logs here.

**Comment by novo-max** [comment]
I can't figure out where the logs are stored. I looked into HOME and /var/log and I can't find it. To clarify I export `export NIXD_FLAGS=-log=verbose` and then I type `codium` within the same shell to start VSCode.

**Comment by inclyc** [comment]
> I can't figure out where the logs are stored. I looked into HOME and /var/log and I can't find it. To clarify I export `export NIXD_FLAGS=-log=verbose` and then I type `codium` within the same shell to start VSCode.

It is in your codium. Same window as the terminal and check 'output', the logs are written there in "Nix" extensiom.

**Comment by novo-max** [comment]
Thank you very much @inclyc . I have to apologize for wasting your time since for a couple of days everything is working just fine and all `sema-def-not-used` do get suppressed when I use the configuration above. Since I created this post I upgraded my NixOS several times so I possibly had outdated "something". All works now! Thank you.
