### ISSUE TITLE
execute fetchers as code action

### ISSUE THREAD

**Issue by MangoIV** [nix-community/nixd#536]
**Is your feature request related to a problem? Please describe.**
often times, you have some fetcher and then you go back to the terminal to execute them to get the hash. It would be immensely useful to have that within `nixd` as a code action or code lense

**Describe the solution you'd like**
when using something like `fetchFromGitHub`, offer to augment the passed attribute set with the hash computed from prefetching it. 

**Describe alternatives you've considered**
n/a

**Additional context**
Another options would be to have a code lens automatically populated whenever the language server detects that there can be soemthing prefetched, e.g.
- language server sees that there's a call to fetchFromGithub
- language server spawns thread that fetches this 
- language server adds code lens that offers to add a `hash =` line to the passed attribute set.

**Comment by inclyc** [comment]
Duplicated to #461
