### ISSUE TITLE
nixpkgs expr using custom nixpkgs path.

### ISSUE THREAD

**Issue by nrakochy** [nix-community/nixd#540]
Hi there, thanks for the great library 🙏 . I’m trying to get autocomplete + Go to Definition for `nix` working in my nvim config, to no avail.  Would you have additional troubleshooting tips? I'm not sure what other steps to take.

I have a custom nixpkgs path that I would like to pull in. Based on the [config docs](https://github.com/nix-community/nixd/blob/main/nixd/docs/configuration.md), I have tried setting the nixpkgs path to nothing (i.e. using the `NIX_PATH` as defined in my shell) as well as

```lua
require("lspconfig").nixd.setup({
   cmd = { "nixd" },
   settings = {
      nixd = {
         nixpkgs = {
            expr = 'import (builtins.getFlake \"path/to/my/custom-nixpkgs\") { }',
         },
    }
})
```
Here's how it appears in my local env, and I believe `variable will bind` is from _nixd_

<img width="485" alt="Screenshot 2024-07-09 at 10 35 05 AM" src="https://github.com/nix-community/nixd/assets/3740177/f2ad8911-4bf4-4c06-a0c7-e2441d23140b">

And the relevant [nvim config is here](https://github.com/nrakochy/init.lua/blob/master/lua/nrakochy/init.lua#L379-L381). Most of this is the baseline template from the nvim kickstart project, so perhaps there's a conflicting config or some such thing. Appreciate any help.

**Comment by inclyc** [comment]
Is `path/to/my/nixpkgs` showned above actually a NixOS/nixpkgs fork?

If so, I think you should use:

import path/to/my/nixpkgs { }

instead of `builtins.getFlake`.

Also it's better to paste logs here, if you can find out where it is.

**Comment by inclyc** [comment]
@nrakochy Is your issue resolved and may I close this?

**Comment by nrakochy** [comment]
Thanks for the prompt replies. Is there anyway to see the loaded nixpkgs config once the server is started? 

I tried multiple variations of the custom path but it seems to be silently failing. 

In terms of logging, I'm away from keys atm but it's sparse. Can send in the AM

**Comment by inclyc** [comment]
>  Is there anyway to see the loaded nixpkgs config once the server is started?

It is in the logs.

**Comment by nrakochy** [comment]
Here are the logs, I added the relevant `expr` at the initialization of each. 

[2024-nixd.log](https://github.com/user-attachments/files/16164305/2024-nixd.log)

> Is path/to/my/nixpkgs showned above actually a NixOS/nixpkgs fork?

When I enter the nix repl and `:lf .` the workspace, here's the result of `builtins.getFlake("/Users/nrakochy/sources/nixpkgs")`, 

<img width="601" alt="nix-repl-import" src="https://github.com/nix-community/nixd/assets/3740177/cef7baf7-4c89-46c9-83fc-e1bbe12d4676">

**Comment by inclyc** [comment]
Then that's wrong, it is NOT nixpkgs. It's a flake.

Please read the comment above, https://github.com/nix-community/nixd/issues/540#issuecomment-2218148489

`nixpkgs`, in nixd, should be some attrset have the same pattern as `import <nixpkgs> { }`. e.g.

```
let
  pkgs = import <nixpkgs> { };
in
  pkgs.hello
```

Then in the configuration you should write `import <nixpkgs> { }`.

**Comment by nrakochy** [comment]
Ah! that makes sense 🤦  Many thanks, appreciate your help

**Comment by inclyc** [comment]
Hi @nrakochy,

> Ah! that makes sense 🤦 Many thanks, appreciate your help

Do you think our documentation is somehow unclear? If so, very appreciate if you can update it to make other users less confusing! You can just edit them on GitHub UI, its really simple.

**Comment by nrakochy** [comment]
I assumed that the attrset would be loaded into the env. I think it's more that I am new to nix 😃

Thanks again
