### ISSUE TITLE
pipe operator

### ISSUE THREAD

**Issue by inclyc** [nix-community/nixd#554]
https://github.com/NixOS/rfcs/pull/148

I really love this syntax. Let's do this in language servers.

**Comment by msfjarvis** [comment]
Lix has [added experimental support](https://gerrit.lix.systems/c/lix/+/1654) for it, is there a possibility to support this in nixd without Nix itself implementing the RFC?

**Comment by viperML** [comment]
@msfjarvis pipe-operator was merged into Nix back in july

**Comment by inclyc** [comment]
> Lix has [added experimental support](https://gerrit.lix.systems/c/lix/+/1654) for it, is there a possibility to support this in nixd without Nix itself implementing the RFC?

This issue mainly addresses pipe operator in libnixf (nixd's parser).

**Comment by c4patino** [comment]
Hi. I noticed that this was merged in a previous version, however I am running into problems where its not properly recognizing the tokens.

  dns =
    [ip "1.1.1.1" "8.8.8.8" "100.100.100.100"]
    |> lib.concatStringsStep " ";

![Image](https://github.com/user-attachments/assets/47301b6c-1152-4ab8-be93-bdd4e67b1e35)

**Comment by ItsLiyua** [comment]
I am also still running into this issue. Is there some experimental setting I have to enable to get support?

**Comment by inclyc** [comment]
> I am also still running into this issue. Is there some experimental setting I have to enable to get support?

This capability was integrated early on without any requirement for experimental flags. Provided you are running nixd version 2.4.0 or higher, the feature should be active by default. If it's still not working, please provide a reproduction case and relevant error logs.
