### ISSUE TITLE
Completion for with pkgs.subpackages

### ISSUE THREAD

**Issue by stasjok** [nix-community/nixd#555]
nixd can complete packages in a construction like

```nix
with pkgs; [
    |
[
```

but it can't complete packages for a construction like

```nix
with pkgs.vimPlugins; [
    |
]
```

I think it will be a nice addition and probably not so hard to implement, especially since it already can complete plain `pkgs.vimPlugins.|`.

**Comment by inclyc** [comment]
Yes, we can do.
