### ISSUE TITLE
Improvements on unused argument detection in `{ foo, bar }@args`

### ISSUE THREAD

**Issue by Aleksanaa** [nix-community/nixd#558]
**Is your feature request related to a problem? Please describe.**
https://github.com/NixOS/nixpkgs/issues/331085

**Describe the solution you'd like**
Don't report unused argument when using together with `@args` pattern, but do report unused argument if they have a default value in this case (the default value won't take effect)

```
nix-repl> foo = { a ? 1 }@args: args

nix-repl> bar = foo {}               

nix-repl> bar
{ }
```

Here `a` should be reported to be unused (maybe add a new error type)

**Additional context**
https://github.com/NixOS/nixpkgs/issues/331085
https://github.com/NixOS/nixpkgs/pull/330589

**Comment by inclyc** [comment]
Maybe split these *two* improvements to *two* issues. The first one seems to be a bug, and bugs usually have higher priority than feature requests.
