### ISSUE TITLE
Syntax highlighting for multi-line strings

### ISSUE THREAD

**Issue by poperigby** [nix-community/nixd#572]
When I was using nil, it would a have syntax highlighting for multi-line strings. For instance, the string following `pkgs.writeShellScriptBin` would automatically have bash syntax highlighting. You could also force it to perform syntax highlighting on a string by putting a comment with the file type before the string, like this:

```nix
# yaml
''
yaml: true
''
```

This would be useful in nixd.

**Comment by inclyc** [comment]
Hi @poperigby,


> When I was using nil, it would a have syntax highlighting for multi-line strings.

The syntax highlighting you described above is likely provided by [tree-sitter-nix](https://github.com/nix-community/tree-sitter-nix). 

Not from LSP server.

So perhaps you need to figure out how to prioritize *tree-sitter*-based syntax highlighting in your editor.

Also, nixd's semantic tokens might have conflicts with that highlighting. Refer the documentation [[features/Semantic Tokens]](https://github.com/nix-community/nixd/blob/main/nixd/docs/features.md#semantic-tokens), you can disable it by `--semantic-tokens=false`, or `export NIXD_FLAGS="--semantic-tokens=false"`.
