### ISSUE TITLE
Command ~/.flox/run/aarch64-darwin.default/bin/nixd not found in $PATH (but it's there)

### ISSUE THREAD

**Issue by nikitavoloboev** [nix-community/nixd#588]
**Describe the bug**
```
which nixd
/Users/nikiv/.flox/run/aarch64-darwin.default/bin/nixd
```

But when i try use it I get:

<img width="514" alt="image" src="https://github.com/user-attachments/assets/8c8ab13a-6536-4445-9ee5-d8aa24de8c6b">

```
  "nix.enableLanguageServer": true,
  "nix.serverPath": "~/.flox/run/aarch64-darwin.default/bin/nixd",
  "nix.formatterPath": "~/.flox/run/aarch64-darwin.default/bin/nixfmt",
  ```
  
  are my vscode settings.

**Comment by inclyc** [comment]
I think this is duplicated to https://github.com/nix-community/vscode-nix-ide/issues/414. And looks like you have resolved it.

**Comment by saikatdas0790** [comment]
@nikitavoloboev How did you solve this exactly? I'm also running into this same issue when opening VSCode connected to a remote host


![Image](https://github.com/user-attachments/assets/37783ecc-bb1e-44c5-a9e0-a3be9bfb1732)

You can see that the nix profile bin is included in the `$PATH` variable as the first entry.

Howevere, I'm seeing this on VSCode

![Image](https://github.com/user-attachments/assets/1067f555-5feb-4fb5-af53-643aa16495c6)

Any idea why?
