### ISSUE TITLE
Hover on NixOS Configuration without type info displayed

### ISSUE THREAD

**Issue by luochen1990** [nix-community/nixd#600]
**Describe the bug**

Hover on NixOS Configuration without type info displayed   when there is `config = { ... }`

**Logs (Required)**

![image](https://github.com/user-attachments/assets/413df0b2-c545-425b-ba2b-4064ab2fd12b)

**Configuration**

```nix
{ ... }:
{
  config = {
    system.stateVersion = "24.05";
  };
}

```

**To Reproduce**

1. paste the above configuration into VScode with Nix plugin and nixd installed.

**Expected behavior**

The type information of option should be displayed here.

**Screenshots**

With `config = { ... }` the type information is not displayed:

![image](https://github.com/user-attachments/assets/efb3d33f-6eda-4bda-99d4-224aaab91c99)

Without `config = { ... }` the type information is displayed correctly:

![image](https://github.com/user-attachments/assets/47929a0b-5660-44b5-bda7-1a2cae8e8f11)

With `config = let in { ... }` the type information is also displayed correctly:

![image](https://github.com/user-attachments/assets/4be325ea-963d-441a-b27b-1b7cb1cffcaf)

**Additional context**

```
$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.10.9-zen1, NixOS, 24.11 (Vicuna), 24.11.20240914.6ca042d`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.24.6`
- nixpkgs: `/nix/store/y6205wq8hxvpqvl8l9d1n9xah01kg0lq-source

$ nixd --version
nixd, version: 2.3.2

$ code --version  # the vscode version
1.93.0
4849ca9bdf9666755eb463db297b69e5385090e3
x64
```

**Comment by inclyc** [comment]
Duplicate to #599

**Comment by inclyc** [comment]
Sorry, I think this actually duplicates to #566, where #599 is slightly different.

**Comment by luochen1990** [comment]
The strange thing is that after I added `let in`, the problem disappeared, so it seems that it's not absolutely rejecting the config. Do you know why this phenomenon occurs?
