### ISSUE TITLE
How to configure nixd to work with home-manager on macOS?

### ISSUE THREAD

**Issue by wojciech-kulik** [nix-community/nixd#608]
Hi,

I'm trying to configure nixd on macOS. I'm using nix-darwin + home-manager. 
However, I can't figure out how it works.

Here is my Neovim config

```lua
lspconfig["nixd"].setup({
  cmd = { "nixd" },
  settings = {
    nixd = {
      nixpkgs = {
        expr = "import <nixpkgs> { }",
      },
      formatting = {
        command = { "nixpkgs-fmt" },
      },
      options = {
        nixos = {
          expr = '(builtins.getFlake "~/repositories/nix-config/flake.nix").darwinConfigurations.Wojciech-MacBook-M1.options',
        },
        -- home_manager = {
        --   -- expr = '(builtins.getFlake "~/repositories/nix-config/flake.nix").darwinConfigurations.Wojciech-MacBook-M1.options.home-manager.users.options',
        --   expr = "(import <home-manager/modules> { configuration = ~/repositories/nix-config/home/default.nix; pkgs = import <nixpkgs> {}; }).options",
        -- },
      },
    },
  },
})
```

It works partially for nix-darwin, I can see things like `system`, `environment`, but I don't see for example nix-darwin specific things like `homebrew`, `system.defaults`, etc.

If I uncomment `home-manager` everything stops working. My nix flake is similar to the one here: https://github.com/nix-community/nixd/issues/269#issue-1939633489

Any help would be appreciated.

**Comment by inclyc** [comment]
Input: 

`(builtins.getFlake "~/repositories/nix-config/flake.nix").darwinConfigurations.Wojciech-MacBook-M1.options`

in `nix-repl`, what is the result?

**Comment by wojciech-kulik** [comment]
I had to use absolute path, but it still shows some error:

```
nix-repl> (builtins.getFlake "/Users/wkulik/repositories/nix-config/flake.nix").darwinConfigurations.Wojciech-MacBook-M1.opt
error:
       … while calling the 'getFlake' builtin
         at «string»:1:2:
            1| (builtins.getFlake "/Users/wkulik/repositories/nix-config/flake.nix").darwinConfigurations.Wojciech-MacBook-M1.options
             |  ^

       error: path '/nix/store/czxkk7x9g3zq83y3xhycckm1vg96hhav-source/flake.nix' does not exist
```

**Comment by wojciech-kulik** [comment]
Oh, I see, I had to use path to directory, not to flake. This one works:

```
options = {
  nixos = {
    expr = '(builtins.getFlake "/Users/wkulik/repositories/nix-config").darwinConfigurations.Wojciech-MacBook-M1.options',
  },
}
```
🎊 

But still the question about home manager remains :)

**Comment by inclyc** [comment]
> But still the question about home manager remains :)

The home-manager option completion works in the same mechanism. If there are something wrong, try to type the expression in Nix REPL and likely there are some errors shown.

**Comment by wojciech-kulik** [comment]
Yes, but I don't know how to get to options. I tried in repl.

**Comment by wojciech-kulik** [comment]
I tried:

```
nix-repl> (builtins.getFlake "github:nix-community/home-manager/master").darwinModules.default { lib = {}; pkgs = {}; config = {}; }
[1/1/2 copied (305.5/361.4 MiB), 56.9 MiB DL] fetching source from https://cache.nixos.org{
  config = «error: undefined variable 'mkMerge'»;
  imports = [ ... ];
}
```

but it leads me nowhere.

**Comment by inclyc** [comment]
Hi @wojciech-kulik, 

> I tried:
> 
> ```
> nix-repl> (builtins.getFlake "github:nix-community/home-manager/master").darwinModules.default { lib = {}; pkgs = {}; config = {}; }
> [1/1/2 copied (305.5/361.4 MiB), 56.9 MiB DL] fetching source from https://cache.nixos.org{
>   config = «error: undefined variable 'mkMerge'»;
>   imports = [ ... ];
> }
> ```


Is your home-manager setup standalone or as-a-darwin-module? Standalone home-manager configuration needs to configure the option system, but as a darwin module, you should see options in the completion list without further configuration.

As I understand the context above, HM is a part of your nix-darwin system, currently nixd cannot deal with it properly because

```nix
home-manager.users.eve = { pkgs, ... }: { # <--- This nested construct is hard to infer.
  home.packages = [ pkgs.atool pkgs.httpie ];
};
```


> 
> but it leads me nowhere.

Sorry for this trouble, I'm glad improve this software to support your needs.

<p align="right">Cheers!</p>

**Comment by wojciech-kulik** [comment]
Oh, I got it now :). Yes, I'm using it as a module. 

Thank you for the help, I can leave without it for now :).

**Comment by Landaman** [comment]
In case anyone is interested, you can sort of hack around this by doing something like the following:
flake.nix:
```
darwinConfigurations.system = nix-darwin.lib.darwinSystem {
        modules = [
          configuration
          home-manager.darwinModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.... = import ./home.nix;
          }
        ];
      };

      # Configurations for typehinting. These aren't really used for anything, just for nixd inference
      editorDarwinConfiguration = self.darwinConfigurations.system
      editorHomeManagerConfiguration = home-manager.lib.homeManagerConfiguration {
        pkgs = self.editorDarwinConfiguration.pkgs; # Inherit pkgs from Darwin
        modules = [ ./home.nix ]; # Load the OS
      };
```

nixd-options:
```
options = {
                ['nix-darwin'] = {
                  expr = '(builtins.getFlake (builtins.toString <flakepath>)).editorDarwinConfiguration.options',
                },
                ['home-manager'] = {
                  expr = '(builtins.getFlake (builtins.toString <flakepath>)).editorHomeManagerConfiguration.options',
                },
              },

```

**Comment by wojciech-kulik** [comment]
I'm not sure what changed, but now the LSP works with home manager without any hacks. Maybe some update to `nixd` fixed that.

**Comment by jessevdp** [comment]
@wojciech-kulik could you please share the expression you're currently using?

---

I've tried the following to no avail..

```nix
(builtins.getFlake "/path/to/my/flake").darwinConfigurations.\"LJQPCW4D95\".config.home-manager.users.\"myusername\".options
```

But while debugging with `nix repl` I can see that `.options` isn't available there.

**Comment by wojciech-kulik** [comment]
I meant LSP in my editor, not inside `nix repl`. Recently, I haven't been using `nix repl` at all.

**Comment by jessevdp** [comment]
I understand. But you have to configure the LSP and point it to your home-manager options right? You use an expression for that.

I’m only using the repl for debugging purposes.

What does your nixd configuration look like that home-manager completion has suddenly started working?

**Comment by wojciech-kulik** [comment]
Oh, right. I use that expression:

```
(builtins.getFlake "/Users/ME/repositories/nix-config").darwinConfigurations.Wojciech-MacBook-M1.options
```

in Neovim via nvim-lspconfig plugin
