### ISSUE TITLE
completion for home-manager nixos module does not work

### ISSUE THREAD

**Issue by mairs8** [nix-community/nixd#611]
**Describe the bug**
I am trying to add completion for my `nixvim` app which is a home-manager module within nixos. I added nixd options for `nixos.expr` and `home-manager.expr` but still no auto-completion works. 

**Configuration**
```nix 
    servers = {
      gopls.enable = true;
      lua-ls.enable = true;
      nixd = {
        enable = true;
        settings = {
          formatting.command = ["nixfmt"];
          nixpkgs.expr = "import (builtins.getFlake \"/home/billy/.dotfiles/NixOS-01\").inputs.nixpkgs { }";
          options = {
            nixos.expr = "(builtins.getFlake \"/home/billy/.dotfiles/NixOS-01\").nixosConfigurations.system.options";
            home-manager.expr = "(builtins.getFlake \"/home/billy/.dotfiles/NixOS-01\").homeConfigurations.\"billy@nixos\".options";
          };
        };
      };
    };
````

**To Reproduce**
go into a `test.nix` file. start typing { plugins.clo }. no autocompletion works on the nixvim options.

**Expected behavior**
it should suggest autocompletion of cloak.

**Comment by inclyc** [comment]
> I added nixd options for `nixos.expr` and `home-manager.expr` but still no auto-completion works.

What did you mean by "no auto-completion works"? Neither NixOS options nor home-manager options work?

> start typing { plugins.clo }. no autocompletion works on the nixvim options.

Type nix expressions you shown in the configuration file in `nix repl`, what is the result?
For example:

```
nix-repl> builtins.getFlake ("/home/billy/.dotfiles/NixOS-01").homeConfigurations."billy@nixos".options

```

If there are some entries begins with `plugin = { ... }` then this is a bug (unlikely I suppose). Otherwise nixd may works as expected, as it cannot determine how to select `{ plugins.clo }`.

**Comment by mairs8** [comment]
@inclyc I am trying to get the options provided by nixvim. If i install nixvim as a standalone package called `nvim`  and then use `nixvim.expr = ''builtins.getFlake ("/home/billy/.dotfiles/NixOS-01").packages.${pkgs.system}.nvim.options'';` the autocompletion for `plugins.cloack` works. 

However my understanding was that if i install nixvim **not** as standalone but **instead** as a [nixos module](https://nix-community.github.io/nixvim/user-guide/install.html), then it's options should be exposed via `nixos.expr = "(builtins.getFlake \"/home/billy/.dotfiles/NixOS-01\").nixosConfigurations.system.options";`. But this doesn't seem to work. is this line just exposing nixos system options to completion? is there any way to expose the nixvim options using something like:
`nixos.expr = "(builtins.getFlake \"/home/billy/.dotfiles/NixOS-01\").nixosConfigurations.packages.nvim.options";`
i have added `inputs.nixosModules.nixvim` to my imports statement in nixos module. 
I am just not sure from the documentation if my thinking is correct or if it is just not possible?

**Comment by inclyc** [comment]
> But this doesn't seem to work

Please provide more context. The source file + cursor where you were typing (better a whole repo), and what did you expect.

**Comment by cooparo** [comment]
> **Describe the bug** I am trying to add completion for my `nixvim` app which is a home-manager module within nixos. I added nixd options for `nixos.expr` and `home-manager.expr` but still no auto-completion works.
> 
> **Configuration**
> 
> ```nix
>     servers = {
>       gopls.enable = true;
>       lua-ls.enable = true;
>       nixd = {
>         enable = true;
>         settings = {
>           formatting.command = ["nixfmt"];
>           nixpkgs.expr = "import (builtins.getFlake \"/home/billy/.dotfiles/NixOS-01\").inputs.nixpkgs { }";
>           options = {
>             nixos.expr = "(builtins.getFlake \"/home/billy/.dotfiles/NixOS-01\").nixosConfigurations.system.options";
>             home-manager.expr = "(builtins.getFlake \"/home/billy/.dotfiles/NixOS-01\").homeConfigurations.\"billy@nixos\".options";
>           };
>         };
>       };
>     };
> ```
> 
> **To Reproduce** go into a `test.nix` file. start typing { plugins.clo }. no autocompletion works on the nixvim options.
> 
> **Expected behavior** it should suggest autocompletion of cloak.

I'm trying to achieve the same, but I think you have to add something more, like a `nixvim.expr` eg.

```nix
nixd = {
  enable = true;
  settings = {
    formatting.command = [ "nixfmt" ];
    nixpkgs.expr = "import <nixpkgs> { }";

    options =
      let
        flake = "(builtins.getFlake \"/PATH/TO/FLAKE)\"";
      in
      {
        # Completitions for nixos and home manager options
        nixos.expr = "${flake}.nixosConfigurations.CONFIGNAME.options";
        home_manager.expr = "${flake}.homeConfigurations.CONFIGNAME.options";

        # nixvim.expr = "(builtins.getFlake \"github:nix-community/nixvim\").*don't know what to put here*.options";
      };
  };
};
```

See also this thread: https://github.com/nix-community/nixvim/issues/2290#issuecomment-2444280910

**Comment by inclyc** [comment]
Ping @mairs8, may I close this issue?

**Comment by cooparo** [comment]
> I am trying to get the options provided by nixvim

@mairs8 See [this](https://github.com/nix-community/nixvim/issues/2290#issuecomment-2445114532) reply, should solve your problem.

**Comment by inclyc** [comment]
Closing this as stale. Feel free to reopen  😄  @mairs8
